export interface Course {
  name: string;
  url: string;
  type: string;
  category: string[];
  difficulty: string;
  duration: string;
}

export const s10: Course[] = [
  // Skill Badges AI/ML
  {
    name: 'Classify Images with TensorFlow on Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/646',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'intermediate',
    duration: '7h15m',
  },
  {
    name: 'Build LookML Objects in Looker',
    url: 'https://www.cloudskillsboost.google/course_templates/639',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '5h15m',
  },
  {
    name: 'Detect Manufacturing Defects using Visual Inspection AI',
    url: 'https://www.cloudskillsboost.google/course_templates/644',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'intermediate',
    duration: '7h15m',
  },
  {
    name: 'Analyze Speech and Language with Google APIs',
    url: 'https://www.cloudskillsboost.google/course_templates/634',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '2h45m',
  },
  {
    name: 'Analyze Images with the Cloud Vision API',
    url: 'https://www.cloudskillsboost.google/course_templates/633',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '3h',
  },
  {
    name: 'Analyze Sentiment with Natural Language API',
    url: 'https://www.cloudskillsboost.google/course_templates/667',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '3h',
  },
  {
    name: 'Perform Predictive Data Analysis in BigQuery',
    url: 'https://www.cloudskillsboost.google/course_templates/656',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'intermediate',
    duration: '4h45m',
  },
  {
    name: 'Create ML Models with BigQuery ML',
    url: 'https://www.cloudskillsboost.google/course_templates/626',
    type: 'skill',
    category: ['ai', 'ml'],
    difficulty: 'intermediate',
    duration: '5h30m',
  },
  // Regular
  {
    name: 'Baseline: Data, ML, AI',
    url: 'https://www.cloudskillsboost.google/course_templates/619',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '5h',
  },
  {
    name: 'Intro to ML: Language Processing',
    url: 'https://www.cloudskillsboost.google/course_templates/740',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '4h',
  },
  {
    name: 'Intro to ML: Image Processing',
    url: 'https://www.cloudskillsboost.google/course_templates/739',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '4h45m',
  },
  {
    name: 'Generative AI Explorer - Vertex AI',
    url: 'https://www.cloudskillsboost.google/course_templates/723',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '4h15m',
  },
  {
    name: 'Google Cloud Computing Foundations: Data, ML, and AI in Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/156',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '8h',
  },
  {
    name: 'Managing Machine Learning Projects with Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/157',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '24h',
  },
  {
    name: 'Introduction to AI and Machine Learning on Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/593',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '8h',
  },
  {
    name: 'Google Cloud Big Data and Machine Learning Fundamentals',
    url: 'https://www.cloudskillsboost.google/course_templates/3',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '5h',
  },
  {
    name: 'Applying Machine Learning to your Data with Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/23',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '16h',
  },
  {
    name: 'Production Machine Learning Systems',
    url: 'https://www.cloudskillsboost.google/course_templates/17',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'intermediate',
    duration: '16h',
  },
  {
    name: 'Smart Analytics, Machine Learning, and AI on Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/55',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'intermediate',
    duration: '7h',
  },
  {
    name: 'ML Pipelines on Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/191',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'advanced',
    duration: '13h15m',
  },
  {
    name: 'Integrating Applications with Gemini 1.0 Pro on Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/980',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '1h45m',
  },
  {
    name: 'Gemini for Data Scientists and Analysts',
    url: 'https://www.cloudskillsboost.google/course_templates/879',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '2h',
  },
  {
    name: 'Gemini for Application Developers',
    url: 'https://www.cloudskillsboost.google/course_templates/881',
    type: 'regular',
    category: ['ai', 'ml'],
    difficulty: 'introductory',
    duration: '1h30m',
  },
  // Skill Badges Infrastructure & Security
  {
    name: 'Create and Manage AlloyDB Instances',
    url: 'https://www.cloudskillsboost.google/course_templates/642',
    type: 'skill',
    category: ['infrastructure', 'security'],
    difficulty: 'introductory',
    duration: '9h30m',
  },
  {
    name: 'Create and Manage Cloud SQL for PostgreSQL Instances',
    url: 'https://www.cloudskillsboost.google/course_templates/652',
    type: 'skill',
    category: ['infrastructure', 'security'],
    difficulty: 'introductory',
    duration: '4h30m',
  },
  {
    name: 'Monitor and Manage Google Cloud Resources',
    url: 'https://www.cloudskillsboost.google/course_templates/653',
    type: 'skill',
    category: ['infrastructure', 'security'],
    difficulty: 'introductory',
    duration: '3h',
  },
  {
    name: 'Manage Kubernetes in Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/783',
    type: 'skill',
    category: ['infrastructure', 'security'],
    difficulty: 'intermediate',
    duration: '5h',
  },
  {
    name: 'Build Infrastructure with Terraform on Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/636',
    type: 'skill',
    category: ['infrastructure', 'security'],
    difficulty: 'intermediate',
    duration: '5h15m',
  },
  // Regular
  {
    name: 'Security Best Practices in Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/87',
    type: 'regular',
    category: ['infrastructure', 'security'],
    difficulty: 'introductory',
    duration: '11h15m',
  },
  {
    name: 'Mitigating Security Vulnerabilities on Google Cloud',
    url: 'https://www.cloudskillsboost.google/course_templates/88',
    type: 'regular',
    category: ['infrastructure', 'security'],
    difficulty: 'introductory',
    duration: '5h',
  },
];
