import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'vi': {
          'de': 'Đức',
          'en': 'Tiếng Anh',
          'fr': 'Pháp',
          'ja': 'Nhật Bản',
          'ko': 'Hàn Quốc',
          'vi': 'Tiếng Việt',
          'zh': 'Trung Quốc',
          'ru': 'Nga',
          'hi': 'Hindi',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid - Trình xác nhận hồ sơ',
          'done': 'Hoàn tất',
          'earned_date': 'Ngày nhận',
          'error_occurred': 'Đã xảy ra lỗi',
          'home': 'Trang chủ',
          'input_hint': 'Nhập tên người dùng hoặc URL hồ sơ của bạn',
          'languages': 'Ngôn ngữ',
          'name': 'Tên',
          'valid': 'Hợp lệ',
          'get_data_failed': 'Lấy dữ liệu thất bại',
          'home_page': 'Trang chủ',
          'result': 'Kết quả',
          'page_not_found': 'Không tìm thấy trang',
          'tier': 'Tier @tier',
          'congratulations': 'Xin chúc mừng, bạn đã đạt Tier @tier',
          'lets_start': 'Bắt đầu thôi, chỉ còn @num ngày nữa là chương trình #ChienBinhAndroid sẽ kết thúc',
          'keep_fighting': 'Cố gắng lên, bạn chỉ cần @num badge nữa là đạt tier 1 rồi',
          'love_it': 'Thích nó?',
          'follow_me_on_github': 'Follow me',
          'star_this_project': 'Star project',
          'invalid_earned_date': 'Thời gian nhận badge của bạn không nằm trong thời gian diễn ra chương trình',
          'invalid_pathway': 'Pathway không nằm trong chương trình',
          'invalid_both_cases': 'Cả thời gian và pathway đều không hợp lệ',
          'seeding': 'Ủng hộ mình bằng cách:',
        },
        'en': {
          'de': 'German',
          'en': 'English',
          'fr': 'French',
          'ja': 'Japanese',
          'ko': 'Korean',
          'vi': 'Vietnamese',
          'zh': 'Chinese',
          'ru': 'Russian',
          'hi': 'Hindi',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid - Profile Validator',
          'done': 'Done',
          'earned_date': 'Earned Date',
          'error_occurred': 'Error Occurred',
          'home': 'Home',
          'input_hint': 'Enter your username or profile URL',
          'languages': 'Languages',
          'name': 'Name',
          'valid': 'Valid',
          'get_data_failed': 'Fetch data failed',
          'home_page': 'Home Page',
          'result': 'Result',
          'page_not_found': 'Page not found',
          'tier': 'Tier @tier',
          'congratulations': 'Congratulations, you have achieved Tier @tier',
          'lets_start': 'Let\'s start, only @num days left until the #ChienBinhAndroid program ends',
          'keep_fighting': 'Keep fighting, you only need @num badge to reach tier 1',
          'love_it': 'Love it?',
          'follow_me_on_github': 'Follow me',
          'star_this_project': 'Star project',
          'invalid_earned_date': 'Your Badge Time Is Not In The Program Time',
          'invalid_pathway': 'Pathway Is Not In The Program',
          'invalid_both_cases': 'Both Time And Pathway Are Not Valid',
          'seeding': 'Support Me By:',
        },
        'zh': {
          'de': '德语',
          'en': '英语',
          'fr': '法语',
          'ja': '日本人',
          'ko': '韩国人',
          'vi': '越南人',
          'zh': '中国人',
          'ru': '俄语',
          'hi': '印地语',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid-个人资料验证器',
          'done': '完毕',
          'earned_date': '赚取的日期',
          'error_occurred': '发生了错误',
          'home': '家',
          'input_hint': '输入您的用户名或个人资料url',
          'languages': '语言',
          'name': '姓名',
          'valid': '有效的',
          'get_data_failed': '获取数据失败',
          'home_page': '主页',
          'result': '结果',
          'page_not_found': '找不到网页',
          'tier': 'Tier @tier',
          'congratulations': '恭喜，您已经取得了@tier的层',
          'lets_start': '让我们开始，只剩下@num的日子，直到#ChienBinhAndroid程序结束',
          'keep_fighting': '继续战斗，您只需要@Num徽章即可到达1级',
          'love_it': '爱它？',
          'follow_me_on_github': '跟我来',
          'star_this_project': 'Star project',
          'invalid_earned_date': '您的徽章时间不在计划的时间',
          'invalid_pathway': '途径不在程序中',
          'invalid_both_cases': '时间和路径均无效',
          'seeding': '支持我：',
        },
        'ja': {
          'de': 'ドイツ人',
          'en': '英語',
          'fr': 'フランス語',
          'ja': '日本',
          'ko': '韓国語',
          'vi': 'ベトナム人',
          'zh': '中国語',
          'ru': 'ロシア',
          'hi': 'ヒンディー語',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid-プロファイルバリデーター',
          'done': '終わり',
          'earned_date': '獲得日',
          'error_occurred': 'エラーが発生しました',
          'home': '家',
          'input_hint': 'ユーザー名またはプロファイルurlを入力します',
          'languages': '言語',
          'name': '名前',
          'valid': '有効',
          'get_data_failed': 'データの取得に失敗しました',
          'home_page': 'ホームページ',
          'result': '結果',
          'page_not_found': 'ページが見つかりません',
          'tier': 'Tier @tier',
          'congratulations': 'おめでとうございます、あなたはティア@tierを達成しました',
          'lets_start': '始めましょう、#ChienBinhAndroidプログラムが終了するまで@num日だけが残っています',
          'keep_fighting': '戦い続けてください、あなたはティア1に到達するために@Numバッジのみが必要です',
          'love_it': '大好きです？',
          'follow_me_on_github': 'フォローしてください',
          'star_this_project': 'Star project',
          'invalid_earned_date': 'バッジの時間はプログラムの時間ではありません',
          'invalid_pathway': '経路はプログラムにありません',
          'invalid_both_cases': '時間と経路の両方が無効です',
          'seeding': '私をサポートしてください：',
        },
        'ko': {
          'de': '독일 사람',
          'en': '영어',
          'fr': '프랑스 국민',
          'ja': '일본어',
          'ko': '한국인',
          'vi': '베트남어',
          'zh': '중국인',
          'ru': '러시아인',
          'hi': '힌디 어',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid- 프로필 유효성 검사기',
          'done': '완료',
          'earned_date': '획득 날짜',
          'error_occurred': '오류가 발생했습니다',
          'home': '집',
          'input_hint': '사용자 이름 또는 프로필 Url을 입력하십시오',
          'languages': '언어',
          'name': '이름',
          'valid': '유효한',
          'get_data_failed': '가져온 데이터가 실패했습니다',
          'home_page': '홈페이지',
          'result': '결과',
          'page_not_found': '페이지를 찾을 수 없습니다',
          'tier': 'Tier @tier',
          'congratulations': '축하합니다. Tier @tier를 달성했습니다',
          'lets_start': '#ChienBinhAndroid 프로그램이 끝날 때까지 @num 날만 남았습니다.',
          'keep_fighting': '계속 싸우십시오. @Num 배지 만 필요합니다.',
          'love_it': '사랑해?',
          'follow_me_on_github': '날 따라 오세요',
          'star_this_project': 'Star project',
          'invalid_earned_date': '배지 시간은 프로그램 시간이 아닙니다',
          'invalid_pathway': '경로는 프로그램에 없습니다',
          'invalid_both_cases': '시간과 경로는 모두 유효하지 않습니다',
          'seeding': '나를 지원합니다 :',
        },
        'de': {
          'de': 'Deutsch',
          'en': 'Englisch',
          'fr': 'Französisch',
          'ja': 'Japanisch',
          'ko': 'Koreanisch',
          'vi': 'Vietnamesisch',
          'zh': 'Chinesisch',
          'ru': 'Russisch',
          'hi': 'Hindi',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid - Profil -Validator',
          'done': 'Erledigt',
          'earned_date': 'Earned Date',
          'error_occurred': 'Ein Fehler Ist Aufgetreten',
          'home': 'Heim',
          'input_hint': 'Geben Sie Ihren Benutzernamen Oder Ihre Profil -Url Ein',
          'languages': 'Sprachen',
          'name': 'Name',
          'valid': 'Gültig',
          'get_data_failed': 'Fetch -Daten Fehlgeschlagen',
          'home_page': 'Startseite',
          'result': 'Ergebnis',
          'page_not_found': 'Seite Nicht Gefunden',
          'tier': 'Tier @tier',
          'congratulations': 'Herzlichen Glückwunsch, Sie Haben Tier @tier Erreicht',
          'lets_start': 'Beginnen Wir, Nur @num Tage Übrig Bis Das #ChienBinhAndroid -Programm Endet',
          'keep_fighting': 'Kämpfe Weiter, Du Brauchst Nur @Num Badge, Um Tier 1 Zu Erreichen',
          'love_it': 'Liebe Es?',
          'follow_me_on_github': 'Folgen Sie Mir',
          'star_this_project': 'Star project',
          'invalid_earned_date': 'Ihre Abzeichenzeit Liegt Nicht In Der Programmzeit',
          'invalid_pathway': 'Pathway Ist Nicht Im Programm',
          'invalid_both_cases': 'Sowohl Die Zeit Als Auch Der Weg Sind Nicht Gültig',
          'seeding': 'Unterstütze Mich Durch:',
        },
        'fr': {
          'de': 'Allemand',
          'en': 'Anglais',
          'fr': 'Français',
          'ja': 'Japonais',
          'ko': 'Coréen',
          'vi': 'Vietnamien',
          'zh': 'Chinois',
          'ru': 'Russe',
          'hi': 'Hindi',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid - Validateur De Profil',
          'done': 'Fait',
          'earned_date': 'Date Gagnée',
          'error_occurred': 'Erreur Est Survenue',
          'home': 'Maison',
          'input_hint': 'Entrez Votre Nom D\'Utilisateur Ou Votre Url De Profil',
          'languages': 'Langues',
          'name': 'Nom',
          'valid': 'Valide',
          'get_data_failed': 'Les Données De Récupération Ont Échoué',
          'home_page': 'Page D\'Accueil',
          'result': 'Résultat',
          'page_not_found': 'Page Non Trouvée',
          'tier': 'Tier @tier',
          'congratulations': 'Félicitations, Vous Avez Réalisé Tier @tier',
          'lets_start': 'Commençons, Il Ne Reste Que Des Jours @num Jusqu\'À Ce Que Le Programme #ChienBinhAndroid Se Termine',
          'keep_fighting': 'Continuez À Vous Battre, Vous N\'Avez Besoin Que D\'Un Badge @Num Pour Atteindre Le Niveau 1',
          'love_it': 'Aimer?',
          'follow_me_on_github': 'Suis-Moi',
          'star_this_project': 'Star project',
          'invalid_earned_date': 'Votre Temps De Badge N\'Est Pas Dans Le Temps Du Programme',
          'invalid_pathway': 'Pathway N\'Est Pas Dans Le Programme',
          'invalid_both_cases': 'Le Temps Et La Voie Ne Sont Pas Valides',
          'seeding': 'Soutenez-Moi Par:',
        },
        'ru': {
          'de': 'Немецкий',
          'en': 'Английский',
          'fr': 'Французский',
          'ja': 'Японский',
          'ko': 'Корейский',
          'vi': 'Вьетнамский',
          'zh': 'Китайский',
          'ru': 'Русский',
          'hi': 'Хинди',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid - Валидатор Профиля',
          'done': 'Сделанный',
          'earned_date': 'Заработанная Дата',
          'error_occurred': 'Возникла Ошибка',
          'home': 'Дом',
          'input_hint': 'Введите Свое Имя Пользователя Или Url',
          'languages': 'Языки',
          'name': 'Имя',
          'valid': 'Действительный',
          'get_data_failed': 'Получить Данные Не Удалось',
          'home_page': 'Домашняя Страница',
          'result': 'Результат',
          'page_not_found': 'Страница Не Найдена',
          'tier': 'Tier @tier',
          'congratulations': 'Поздравляю, Вы Достигли Уровня @tier',
          'lets_start': 'Давайте Начнем, Остались Только Дни @num, Пока Не Закончится Программа #ChienBinhAndroid',
          'keep_fighting': 'Продолжайте Сражаться, Вам Нужен Только Значок @Num, Чтобы Достичь Уровня 1',
          'love_it': 'Любить Это?',
          'follow_me_on_github': 'Подписывайтесь На Меня',
          'star_this_project': 'Star project',
          'invalid_earned_date': 'Время Вашего Значка Не Во Время Программы',
          'invalid_pathway': 'Путь Не В Программе',
          'invalid_both_cases': 'И Время, И Путь Недопустимы',
          'seeding': 'Поддержите Меня:',
        },
        'hi': {
          'de': 'जर्मन',
          'en': 'अंग्रेज़ी',
          'fr': 'फ्रांसीसी',
          'ja': 'जापानी',
          'ko': 'कोरियाई',
          'vi': 'वियतनामी',
          'zh': 'चीनी',
          'ru': 'रूसी',
          'hi': 'हिंदी',
          'github': 'GitHub',
          'app_title': 'ChienBinhAndroid - प्रोफ़ाइल सत्यापनकर्ता',
          'done': 'पूर्ण',
          'earned_date': 'अर्जित तिथि',
          'error_occurred': 'त्रुटि हुई',
          'home': 'घर',
          'input_hint': 'अपना उपयोगकर्ता नाम या प्रोफ़ाइल Url दर्ज करें',
          'languages': 'बोली',
          'name': 'नाम',
          'valid': 'वैध',
          'get_data_failed': 'डेटा विफल',
          'home_page': 'गृह पृष्ठ',
          'result': 'परिणाम',
          'page_not_found': 'पृष्ठ नहीं मिला',
          'tier': 'Tier @tier',
          'congratulations': 'बधाई हो, आपने Tier @tier प्राप्त किया है',
          'lets_start': 'चलो शुरू करते हैं, केवल @num दिन तब तक बचे हैं जब तक कि #ChienBinhAndroid प्रोग्राम समाप्त नहीं हो जाता',
          'keep_fighting': 'लड़ते रहें, आपको केवल टियर 1 तक पहुंचने के लिए @Num बैज की आवश्यकता है',
          'love_it': 'इसे प्यार करना?',
          'follow_me_on_github': 'मेरे पीछे आओ',
          'star_this_project': 'Star project',
          'invalid_earned_date': 'आपका बैज समय कार्यक्रम के समय में नहीं है',
          'invalid_pathway': 'मार्ग कार्यक्रम में नहीं है',
          'invalid_both_cases': 'समय और मार्ग दोनों मान्य नहीं हैं',
          'seeding': 'मेरा समर्थन करें:',
        },

      };

  static const supportedLanguages = [
    'vi',  'en',  'zh',  'ja',  'ko',  'de',  'fr',  'ru',  'hi',
  ];
}